/*
 * PacketIds.h
 *
 *  Created on: Mar 25, 2012
 *      Author: Mitchell
 */

#ifndef PACKETIDS_H_
#define PACKETIDS_H_

#define PACKETID_DEVICE_BOOT 0

#define PACKETID_PING_REQUEST 1

#define PACKETID_PING_RESPONSE 2

#define PACKETID_ERROR_MESSAGE 3

#define PACKETID_GLOBAL_CONFIGURE_REQUEST 4

#define PACKETID_GLOBAL_CONFIGURE_RESPONSE 5

#define PACKETID_OBJECT_CONFIGURE_REQUEST 6

#define PACKETID_OBJECT_CONFIGURE_RESPONSE 7

#define PACKETID_MESSAGE 8

#define PACKETID_BULK_INPUT_VALUE 9

#define PACKETID_BULK_OUTPUT_VALUE 10


#endif /* PACKETIDS_H_ */
